/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conjugaison;


import java.awt.Font;
import java.nio.charset.Charset;
import java.sql.ResultSet;
import java.sql.SQLException;
import  javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class JeConjugue extends javax.swing.JFrame {

    /**
     * Creates new form JeConjugue
     */
     MysqlConnexion connexion=  new MysqlConnexion("verbes","root","");
    public JeConjugue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imparfait = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        futuranterieur = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        present = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        plusqueparfait = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        futursimple = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        passecompose = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        passesimple = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        passeanterieur = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reviser = new javax.swing.JButton();
        quitter = new javax.swing.JButton();
        evaluer = new javax.swing.JButton();
        groupe1 = new javax.swing.JComboBox<>();
        groupe3 = new javax.swing.JComboBox<>();
        groupe2 = new javax.swing.JComboBox<>();
        entrerverbe = new javax.swing.JTextField();
        conjuguer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imparfait.setBackground(new java.awt.Color(0, 0, 0));
        imparfait.setColumns(20);
        imparfait.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        imparfait.setForeground(new java.awt.Color(255, 255, 255));
        imparfait.setRows(5);
        jScrollPane1.setViewportView(imparfait);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 240, 190));

        futuranterieur.setBackground(new java.awt.Color(0, 0, 0));
        futuranterieur.setColumns(20);
        futuranterieur.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        futuranterieur.setForeground(new java.awt.Color(255, 255, 255));
        futuranterieur.setRows(5);
        jScrollPane2.setViewportView(futuranterieur);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 270, 190));

        present.setBackground(new java.awt.Color(0, 0, 0));
        present.setColumns(20);
        present.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        present.setForeground(new java.awt.Color(255, 255, 255));
        present.setRows(5);
        jScrollPane3.setViewportView(present);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 240, 190));

        plusqueparfait.setBackground(new java.awt.Color(0, 0, 0));
        plusqueparfait.setColumns(20);
        plusqueparfait.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        plusqueparfait.setForeground(new java.awt.Color(255, 255, 255));
        plusqueparfait.setRows(5);
        jScrollPane4.setViewportView(plusqueparfait);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 250, 190));

        futursimple.setBackground(new java.awt.Color(0, 0, 0));
        futursimple.setColumns(20);
        futursimple.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        futursimple.setForeground(new java.awt.Color(255, 255, 255));
        futursimple.setRows(5);
        jScrollPane5.setViewportView(futursimple);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 250, 190));

        passecompose.setBackground(new java.awt.Color(0, 0, 0));
        passecompose.setColumns(20);
        passecompose.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        passecompose.setForeground(new java.awt.Color(255, 255, 255));
        passecompose.setRows(5);
        jScrollPane6.setViewportView(passecompose);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 250, 190));

        passesimple.setBackground(new java.awt.Color(0, 0, 0));
        passesimple.setColumns(20);
        passesimple.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        passesimple.setForeground(new java.awt.Color(255, 255, 255));
        passesimple.setRows(5);
        passesimple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane7.setViewportView(passesimple);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 230, 190));

        passeanterieur.setBackground(new java.awt.Color(0, 0, 0));
        passeanterieur.setColumns(20);
        passeanterieur.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        passeanterieur.setForeground(new java.awt.Color(255, 255, 255));
        passeanterieur.setRows(5);
        jScrollPane8.setViewportView(passeanterieur);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 250, 190));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Présent");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Passé Simple");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 61, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Futur Simple");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 61, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Passé Composé");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Passé antérieur ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Plus que parfait  ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Futur antérieur");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, 27));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Imparfait");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 66, -1, -1));

        reviser.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        reviser.setForeground(new java.awt.Color(0, 0, 153));
        reviser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/reviser.png"))); // NOI18N
        reviser.setText("Réviser");
        reviser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviserActionPerformed(evt);
            }
        });
        getContentPane().add(reviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 440, 190, 70));

        quitter.setForeground(new java.awt.Color(0, 0, 153));
        quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/quit-icon.png"))); // NOI18N
        quitter.setText("Quitter");
        getContentPane().add(quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 610, 190, 72));

        evaluer.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        evaluer.setForeground(new java.awt.Color(0, 0, 153));
        evaluer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/quiz.png"))); // NOI18N
        evaluer.setText("Evaluer");
        evaluer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluerActionPerformed(evt);
            }
        });
        getContentPane().add(evaluer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 520, 190, 73));

        groupe1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        groupe1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er groupe" }));
        groupe1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupe1ItemStateChanged(evt);
            }
        });
        getContentPane().add(groupe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 330, 176, -1));

        groupe3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        groupe3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 ème groupe" }));
        groupe3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupe3ItemStateChanged(evt);
            }
        });
        groupe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupe3ActionPerformed(evt);
            }
        });
        getContentPane().add(groupe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, 176, -1));

        groupe2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        groupe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2ème groupe" }));
        groupe2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupe2ItemStateChanged(evt);
            }
        });
        getContentPane().add(groupe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, 176, -1));

        entrerverbe.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        entrerverbe.setName(""); // NOI18N
        entrerverbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrerverbeActionPerformed(evt);
            }
        });
        getContentPane().add(entrerverbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 210, 40));

        conjuguer.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        conjuguer.setForeground(new java.awt.Color(0, 0, 153));
        conjuguer.setText("Conjuguer");
        conjuguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conjuguerActionPerformed(evt);
            }
        });
        getContentPane().add(conjuguer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 180, 40));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("1er Groupe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("2ème Groupe");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("3ème Groupe");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Entrer le verbe");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/conjugaison.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 440, 268));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/fond_gene.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1370, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrerverbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrerverbeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrerverbeActionPerformed

    private void groupe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupe3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupe3ActionPerformed


    
    
    
    
    
    private void conjuguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjuguerActionPerformed
        // TODO add your handling code here:
        //On reinitialise les combobox des groupes:
        groupe1.setSelectedIndex(0);
        groupe2.setSelectedIndex(0);
        groupe3.setSelectedIndex(0);
        //
        final Charset UTF_8=Charset.forName("UTF-8");
	final Charset ISO=Charset.forName("ISO-8859-1");
       
       //
       String conj_irr=new String("");
        Verbe verbe;
        verbe=new Verbe(entrerverbe.getText());
        if(verbe!=null){
            //
            
            if(verbe.est_pronominal()){
                verbe.enlever();
            }
            //Si le verbe existe dans la base de donnees
            verbe.connecter();
            if(verbe.verbe_exist()){
                  
                //si le verbe est irregulier
                if(verbe.est_irregulier()){
                    //****
                        present.setText("");
                        passecompose.setText("");
                        imparfait.setText("");    
                        plusqueparfait.setText("");
                        passesimple.setText("");    
                        passeanterieur.setText("");       
                        futursimple.setText("");      
                        futuranterieur.setText("");       
                    ResultSet irregulier;
                    try{
                    irregulier=connexion.SQLSelect("Select * from verbe_irregulier where Lower(verbes) like '"+verbe.getVerbe()+"'");
                    while(irregulier.next()){
                        present.append(irregulier.getString(3));
                        passecompose.append(irregulier.getString(4));
                        imparfait.append(irregulier.getString(5));     
                        plusqueparfait.append(irregulier.getString(6));
                        passesimple.append(irregulier.getString(7));        
                        passeanterieur.append(irregulier.getString(8));        
                        futursimple.append(irregulier.getString(9));        
                        futuranterieur.append(irregulier.getString(10));        
                    }
                    }
                    catch(SQLException e){
                         JOptionPane jop1;
                         jop1=new JOptionPane();
                         jop1.showMessageDialog(null,"Votre verbe n'est pas pris en compte par notre application");
                    }
                }
                //si le verbe est regulier
                else{
                  
                    verbe.conjuguer_regulier(present,passecompose,imparfait,plusqueparfait,passesimple,passeanterieur,futursimple,futuranterieur);
                }
               Fichier fichier =new Fichier("conjugaison//a_reviser.txt");
               conj_irr=verbe.getVerbe();
               fichier.ecrire(conj_irr+"\n");
               fichier.fermer_fichier();
            }
            //Si le verbe n,existe pas dans la base de donnees
            else{
                JOptionPane jop1;
                 jop1=new JOptionPane();
                 jop1.showMessageDialog(null,"Votre verbe n'est pas pris en compte par notre application");
            }
        }
        else{
            present.append("Le contenu est a null");
        }
    }//GEN-LAST:event_conjuguerActionPerformed

    private void reviserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviserActionPerformed
        // TODO add your handling code here:
        Revision revision=new Revision();
        this.hide();
        revision.setVisible(true);
    }//GEN-LAST:event_reviserActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        entrerverbe.setFont(new Font("Arial Unicode MS", Font.PLAIN,12));
       
        connexion.connect();
        ResultSet group1;
        ResultSet group2;
        ResultSet group3;
        try{
        group1=connexion.SQLSelect("Select verbes from groupe1");
        while(group1.next()){
            groupe1.addItem(group1.getString(1));
        }
        group2=connexion.SQLSelect("Select verbes from groupe2");
        while(group2.next()){
            groupe2.addItem(group2.getString(1));
        }
        group3=connexion.SQLSelect("Select distinct verbes from verbe_irregulier");
        while(group3.next()){
            groupe3.addItem(group3.getString(1));
        }
        }
        catch(SQLException e){
            System.out.println("Impossible d'executer une des requetes");
        }
    }//GEN-LAST:event_formWindowOpened

    private void groupe1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupe1ItemStateChanged
        // TODO add your handling code here:
        if(groupe1.getSelectedItem().toString().compareTo("1er groupe")!=0){
        groupe2.setSelectedIndex(0);
        groupe3.setSelectedIndex(0);
        entrerverbe.setText("");
        entrerverbe.setText(groupe1.getSelectedItem().toString());
        }
    }//GEN-LAST:event_groupe1ItemStateChanged

    private void evaluerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluerActionPerformed
        // TODO add your handling code here:
        Evaluation evaluation=new Evaluation();
        evaluation.setVisible(true);
        this.hide();
    }//GEN-LAST:event_evaluerActionPerformed

    private void groupe2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupe2ItemStateChanged
        // TODO add your handling code here:
        if(groupe2.getSelectedItem().toString().compareTo("2ème groupe")!=0){
        groupe1.setSelectedIndex(0);
        groupe3.setSelectedIndex(0);
        entrerverbe.setText("");
        entrerverbe.setText(groupe2.getSelectedItem().toString());
        }
    }//GEN-LAST:event_groupe2ItemStateChanged

    private void groupe3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupe3ItemStateChanged
        // TODO add your handling code here:
        if(groupe3.getSelectedItem().toString().compareTo("3 ème groupe")!=0){
        groupe1.setSelectedIndex(0);
        groupe2.setSelectedIndex(0);
        entrerverbe.setText("");
        entrerverbe.setText(groupe3.getSelectedItem().toString());
        }
    }//GEN-LAST:event_groupe3ItemStateChanged

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeConjugue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeConjugue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeConjugue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeConjugue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeConjugue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conjuguer;
    private javax.swing.JTextField entrerverbe;
    private javax.swing.JButton evaluer;
    private javax.swing.JTextArea futuranterieur;
    private javax.swing.JTextArea futursimple;
    private javax.swing.JComboBox<String> groupe1;
    private javax.swing.JComboBox<String> groupe2;
    private javax.swing.JComboBox<String> groupe3;
    private javax.swing.JTextArea imparfait;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea passeanterieur;
    private javax.swing.JTextArea passecompose;
    private javax.swing.JTextArea passesimple;
    private javax.swing.JTextArea plusqueparfait;
    private javax.swing.JTextArea present;
    private javax.swing.JButton quitter;
    private javax.swing.JButton reviser;
    // End of variables declaration//GEN-END:variables

    


}
