/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conjugaison;

import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class Revision extends javax.swing.JFrame {
int iterateur=0;
String cours[]={"p1.PNG","p2.PNG","p2_bis.PNG","p3.PNG","p4.PNG","p5.PNG","p6.PNG","p7.PNG","p8.PNG","p9.PNG","p10.PNG","p11.PNG","p12.PNG","p13.PNG","p14.PNG","p15.PNG","p16.PNG"};

    /**
     * Creates new form Revision
     */
    public Revision() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NoPage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_verbes_a_reviser = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        combo_verbes_a_reviser = new javax.swing.JComboBox<>();
        cours_conjugaison = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Il revise.. .");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 150, 90));

        NoPage.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        NoPage.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(NoPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 790, 60));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Je revis(e/es)?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 90));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tu revises  .. .");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 150, 90));

        table_verbes_a_reviser.setBackground(new java.awt.Color(0, 0, 0));
        table_verbes_a_reviser.setColumns(20);
        table_verbes_a_reviser.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        table_verbes_a_reviser.setForeground(new java.awt.Color(255, 255, 255));
        table_verbes_a_reviser.setRows(5);
        jScrollPane2.setViewportView(table_verbes_a_reviser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 350, 530));

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 153));
        jButton8.setText("Cours Sur Le Groupe 2");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 870, 60));

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("<<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 50, 540));

        jButton10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setText(">>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 130, 50, 540));

        combo_verbes_a_reviser.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        combo_verbes_a_reviser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "verbes étudiés" }));
        combo_verbes_a_reviser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_verbes_a_reviserItemStateChanged(evt);
            }
        });
        getContentPane().add(combo_verbes_a_reviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 60));

        cours_conjugaison.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        getContentPane().add(cours_conjugaison, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 780, 480));

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/quiz.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 50));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/books-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjugaison/photos/fond_gene.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Fichier fichier =new Fichier("conjugaison//a_reviser.txt");
        String verbe_a_reviser=new String("er");
        verbe_a_reviser=fichier.lire(); 
        while(verbe_a_reviser!=null){
        combo_verbes_a_reviser.addItem(verbe_a_reviser);
        verbe_a_reviser=fichier.lire();
        }
        fichier.fermer_fichier();
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
       
       if(iterateur<cours.length){
           
           ImageIcon  icone= new ImageIcon("conjugaison//revision//cours_de_base//"+cours[iterateur]);
           cours_conjugaison.setIcon(icone); 
           NoPage.setText(""+(iterateur+1)+"/"+cours.length);
           iterateur++;
       }
       else{
           iterateur=0;
           ImageIcon  icone=  new ImageIcon("conjugaison//revision//cours_de_base//"+cours[iterateur]);
           cours_conjugaison.setIcon(icone); 
           NoPage.setText(""+(iterateur+1)+"/"+cours.length);
            iterateur++;
       }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        if(iterateur>0){
           iterateur--;
           ImageIcon  icone= new ImageIcon("/conjugaison/revision/cours_de_base/"+cours[iterateur]);
           cours_conjugaison.setIcon(icone);
            NoPage.setText(""+(iterateur+1)+"/"+cours.length);
         }
        else{
             iterateur=cours.length-1;
              NoPage.setText(""+(iterateur+1)+"/"+cours.length);
             ImageIcon  icone= new ImageIcon("/conjugaison/revision/cours_de_base/"+cours[iterateur]);
             cours_conjugaison.setIcon(icone);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void combo_verbes_a_reviserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_verbes_a_reviserItemStateChanged
        // TODO add your handling code here:
        Verbe verbe=new Verbe(combo_verbes_a_reviser.getSelectedItem().toString());
        if(verbe!=null){
            //
            
            if(verbe.est_pronominal()){
                verbe.enlever();
            }
            //Si le verbe existe dans la base de donnees
            verbe.connecter();
                  
                //si le verbe est irregulier
                if(verbe.est_irregulier()){
                    //****
                }
                //si le verbe est regulier
                else{
                  
                    verbe.conjuguer_regulier_revision(table_verbes_a_reviser);
                }
        }
                
    }//GEN-LAST:event_combo_verbes_a_reviserItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JeConjugue conjugaison=new JeConjugue();
        conjugaison.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Evaluation evaluation=new Evaluation();
        evaluation.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoPage;
    private javax.swing.JComboBox<String> combo_verbes_a_reviser;
    private javax.swing.JLabel cours_conjugaison;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea table_verbes_a_reviser;
    // End of variables declaration//GEN-END:variables
}
